name: Docker Image CI CD

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build client image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-client ./client

    - name: Build server image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-server ./server

    - name: Push client image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/chat-client

    - name: Push server image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/chat-server

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          docker pull ${{ secrets.DOCKER_USERNAME }}/chat-client
          docker pull ${{ secrets.DOCKER_USERNAME }}/chat-server

          docker stop chat-client || true && docker rm chat-client || true
          docker stop chat-server || true && docker rm chat-server || true

          docker run -d --name chat-client -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/chat-client
          docker run -d --name chat-server -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/chat-server